Parameters:
  sshKey:
    Description: EC2 keypair for SSH access
    Type: String
Resources:
  PiholeInstance:
    Type : 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref PiholeSecurityGroup
      KeyName: !Ref sshKey
      ImageId: ami-00399ec92321828f5
      InstanceType: t2.micro
      Volumes:
        - !Ref PiholeEBSDisk
  PiholeSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: DNS server rules
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          toPort: 80
          CidrIp: 0.0.0.0/0
  PiholeEBSDisk:
    Type: 'AWS::EC2::Volume'
    Properties:
      VolumeType: gp3
      Size: 30